version: "3.4"

services:

  postgres:
    # container_name: postgres_renta
    # image: postgres:13
    # ports:
    #   - "5432:5432"
    # environment:
    #   POSTGRES_USER: username
    #   POSTGRES_PASSWORD: mypassword
    #   POSTGRES_DB: college_db
    container_name: postgres_rentacar
    image: postgres
    user: root
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    # volumes:
    #   - ${BASE_PATH}/postgres:/var/lib/postgresql/data
    #   - ${BASE_PATH}/pgbckp:/pgbckp

  mongodb:
    image: 'mongo'
    container_name: "mongodb-rent"
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
    # volumes:
    #   - mongo:/data/db
